print("Welcome to the tip calculator.")
bill = input("What was the total bill? $")
people = input("How many people split the bill? ")
percent = input("What percentage tip would you like to give? 10, 12 or 15? ")
pay = float(bill)/float(people)*(1+float(percent)/100)
final_pay = round(pay, 2)
print(f"Each person should pay: ${final_pay}")
